### ISSUE TITLE
Users to be reprompted when they have no name

### ISSUE THREAD

**Issue by rjmk** [dwyl/sort#1]
We need to copy over the functionality from https://github.com/dwyl/hapi-socketio-redis-chat-example/pull/34

**Comment by rjmk** [comment]
This change needs to be propagated through all the branches. Suggestions for how to do this?

**Comment by nelsonic** [comment]
@rafe We can cherry pick the commits, but I usually just copy-paste the code into a branch, merge that into master and then when people PR their branches they re-base on master.
