### ISSUE TITLE
Explain the links to the commits in the readme and how to use

### ISSUE THREAD

**Issue by rjmk** [dwyl/sort#8]
The readme links to the different stages of the app through the commits. We should explain what's happening and how to make use of it.

**Comment by rjmk** [comment]
Can we link to the diffs between commits to make them more useful?

**Comment by rjmk** [comment]
Yes! https://github.com/dwyl/hapi-socketio-redis-riot-chat-example/compare/6cd72e0e4e18beffe8574847d91a7da1677e2988...b755c52189805c0a402753cefecc2ae069a21383

The syntax is /compare/[older commit hash]...[newer commit hash]

**Comment by iteles** [comment]
Oooooooh! Are you happy to PR this in @rjmk ?

**Comment by rjmk** [comment]
Sure!

**Comment by nelsonic** [comment]
I'm _excited_! :+1:

**Comment by rjmk** [comment]
Closed in #12

**Comment by nelsonic** [comment]
Thanks for tidying up @rjmk 👍  
❤️  ✅
